package com.example.ui.localization

object StringsLocalization {
    fun get(key: String, lang: AppLanguage): String {
        val dict = if (lang == AppLanguage.HINDI) hindiStrings else englishStrings
        return dict[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        "app_title" to "Quiz & Earn",
        "home" to "Home",
        "quiz" to "Quiz",
        "tasks" to "Tasks",
        "wallet" to "Wallet",
        "profile" to "Profile",
        "admin" to "Admin",
        "total_coins" to "Total Coins",
        "daily_bonus" to "Daily Bonus",
        "claim_now" to "Claim 25 Coins",
        "claimed_today" to "Claimed Today",
        "next_bonus_in" to "Next bonus in",
        "featured_quizzes" to "Featured Quizzes",
        "earn_coins_desc" to "Play trivia & win up to 50 coins!",
        "view_all" to "View All",
        "pending_tasks" to "Available Tasks",
        "complete_earn" to "Complete & earn 50 coins each",
        "redeem_goal" to "Redeem Goal",
        "redeem_now" to "Redeem Now",
        "coins_needed" to "coins needed to redeem ₹20",
        "ready_to_redeem" to "Ready to redeem ₹20 reward!",
        "recent_activity" to "Recent Activity",
        "no_activity" to "No transactions yet. Play a quiz or complete a task!",
        
        // Quiz
        "all_categories" to "All Categories",
        "gk" to "General Knowledge",
        "science" to "Science & Nature",
        "sports" to "Sports & Games",
        "technology" to "Technology & AI",
        "daily_quiz" to "Daily Special Quiz",
        "questions_count" to "Questions",
        "time_per_q" to "Seconds per question",
        "start_quiz" to "Start Quiz",
        "quiz_completed" to "Quiz Completed",
        "quiz_already_rewarded" to "Quiz reward already claimed!",
        "quiz_results" to "Quiz Results",
        "your_score" to "Your Score",
        "coins_earned" to "Coins Earned",
        "congratulations" to "Congratulations!",
        "play_another" to "Play Another Quiz",
        "back_to_home" to "Back to Home",
        
        // Tasks
        "daily_tasks" to "Earn by Tasks",
        "task_reward" to "+50 Coins",
        "status_pending" to "Pending",
        "status_completed" to "Completed",
        "start_task" to "Start Task",
        "verifying_task" to "Verifying task completion...",
        "task_success" to "Task verified! 50 Coins added to wallet.",
        "task_already_done" to "Task already completed. No duplicate rewards.",
        "follow_instagram_title" to "Follow @devrajlohar0981",
        "follow_instagram_desc" to "Follow devrajlohar0981 on Instagram & earn 50 Coins",
        "subscribe_youtube_title" to "Subscribe total video DK",
        "subscribe_youtube_desc" to "Subscribe to 'total video DK' on YouTube & earn 50 Coins",
        "creator_channels" to "Official Creator Channels",
        "follow_now" to "Follow Now",
        "subscribe_now" to "Subscribe",

        // Cool Features
        "scratch_card" to "Lucky Scratch Card",
        "scratch_to_win" to "Scratch & Win up to 100 Coins!",
        "scratch_now" to "Scratch Now",
        "scratched_today" to "Card Scratched",
        "streak_booster" to "7-Day Streak Booster",
        "streak_desc" to "Check-in daily to unlock up to 100 free coins!",
        "refer_earn" to "Refer & Earn",
        "refer_desc" to "Invite friends & get 100 coins each!",
        "copy_referral" to "Copy Code",
        "share_invite" to "Share on WhatsApp",
        "leaderboard" to "Top Earners Leaderboard",
        
        // Wallet & Redeem - Play Store & UPI Cashback
        "wallet_balance" to "Wallet Balance",
        "estimated_value" to "Equivalent Value",
        "transaction_history" to "Transaction History",
        "filter_all" to "All",
        "filter_earned" to "Earned (+)",
        "filter_redeemed" to "Redeemed (-)",
        "choose_reward" to "Redeem Coins",
        "rule_1200_coins" to "1200 Coins = ₹20 (Play Store / UPI)",
        "insufficient_balance" to "Insufficient balance. Minimum 600 coins required.",
        "payout_method" to "Select Payout Method",
        "enter_account" to "Enter Account Details",
        "submit_redeem" to "Submit Redeem Request",
        "redeem_submitted" to "Redeem request submitted successfully!",
        "redeem_history" to "Redemption History",
        "redeem_code" to "Your Play Store Redeem Code",
        "status_processing" to "Processing",
        "status_rejected" to "Rejected",
        
        // Play Store & UPI Specific
        "play_store_redeem_code" to "Play Store Redeem Code",
        "upi_instant_cashback" to "UPI Instant Cashback",
        "tab_all_rewards" to "All Rewards",
        "tab_play_store" to "Play Store Codes",
        "tab_upi" to "UPI Cashback",
        "copy_code" to "Copy Code",
        "code_copied" to "Redeem code copied to clipboard!",
        "open_play_store" to "Redeem on Play Store",
        "upi_utr_ref" to "Bank UTR Reference",
        "cashback_credited" to "Cashback Credited Successfully",
        "instant_transfer_badge" to "⚡ Instant 5-Minute Transfer",
        "play_store_instructions" to "How to redeem: Open Play Store > Tap Profile Icon > Payments & Subscriptions > Redeem code.",
        "upi_cashback_note" to "Instant direct transfer to your Bank Account via Google Pay, PhonePe, Paytm or BHIM UPI.",

        // Profile & Auth
        "login" to "Login",
        "signup" to "Sign Up",
        "email" to "Email Address",
        "password" to "Password",
        "full_name" to "Full Name",
        "mobile" to "Mobile Number",
        "sign_in_button" to "Sign In",
        "create_account" to "Create Account",
        "quick_test_login" to "Quick Demo Login (User)",
        "quick_admin_login" to "Quick Demo Login (Admin)",
        "logout" to "Sign Out",
        "account_blocked" to "This account has been blocked by Admin.",
        "admin_dashboard" to "Admin Dashboard",
        "app_language" to "App Language",
        "dark_mode" to "Dark Mode",
        
        // Admin
        "admin_panel" to "Admin Control Panel",
        "overview" to "Overview",
        "users" to "Users",
        "redeem_requests" to "Redeem Requests",
        "redeem_codes" to "Redeem Codes",
        "manage_quizzes" to "Quizzes & Tasks",
        "total_users" to "Total Users",
        "coins_in_circ" to "Total Coins in Circulation",
        "pending_redemptions" to "Pending Redemptions",
        "total_paid_out" to "Total Paid Out (₹)",
        "approve" to "Approve & Send Reward",
        "reject" to "Reject & Refund",
        "add_code" to "Add Redeem Code",
        "code_input" to "e.g. 3K7X-9PLQ-8B2M-W4TN",
        "block_user" to "Block User",
        "unblock_user" to "Unblock User"
    )

    private val hindiStrings = mapOf(
        "app_title" to "क्विज़ और कमाएं",
        "home" to "होम",
        "quiz" to "क्विज़",
        "tasks" to "टास्क",
        "wallet" to "वॉलेट",
        "profile" to "प्रोफ़ाइल",
        "admin" to "एडमिन",
        "total_coins" to "कुल कॉइन्स",
        "daily_bonus" to "दैनिक बोनस",
        "claim_now" to "25 कॉइन प्राप्त करें",
        "claimed_today" to "आज प्राप्त कर लिया",
        "next_bonus_in" to "अगला बोनस",
        "featured_quizzes" to "खास क्विज़",
        "earn_coins_desc" to "सवालों के जवाब दें और 50 कॉइन्स जीतें!",
        "view_all" to "सभी देखें",
        "pending_tasks" to "उपलब्ध टास्क",
        "complete_earn" to "पूरा करें और 50 कॉइन कमाएं",
        "redeem_goal" to "रिडीम लक्ष्य",
        "redeem_now" to "अभी रिडीम करें",
        "coins_needed" to "कॉइन ₹20 पाने के लिए चाहिए",
        "ready_to_redeem" to "बधाई! आप ₹20 रिडीम कर सकते हैं",
        "recent_activity" to "हाल की गतिविधि",
        "no_activity" to "अभी कोई लेन-देन नहीं है। क्विज़ खेलें या टास्क पूरा करें!",
        
        // Quiz
        "all_categories" to "सभी श्रेणियां",
        "gk" to "सामान्य ज्ञान",
        "science" to "विज्ञान एवं प्रकृति",
        "sports" to "खेलकूद",
        "technology" to "तकनीक एवं एआई",
        "daily_quiz" to "दैनिक विशेष क्विज़",
        "questions_count" to "प्रश्न",
        "time_per_q" to "सेकंड प्रति प्रश्न",
        "start_quiz" to "क्विज़ शुरू करें",
        "quiz_completed" to "क्विज़ पूरा हुआ",
        "quiz_already_rewarded" to "इस क्विज़ का इनाम पहले ही लिया जा चुका है!",
        "quiz_results" to "क्विज़ परिणाम",
        "your_score" to "आपका स्कोर",
        "coins_earned" to "कमाए गए कॉइन",
        "congratulations" to "बधाई हो!",
        "play_another" to "दूसरा क्विज़ खेलें",
        "back_to_home" to "होम पर जाएं",
        
        // Tasks
        "daily_tasks" to "टास्क से कमाएं",
        "task_reward" to "+50 कॉइन",
        "status_pending" to "बाकी है",
        "status_completed" to "पूर्ण",
        "start_task" to "टास्क शुरू करें",
        "verifying_task" to "सत्यापित किया जा रहा है...",
        "task_success" to "टास्क सत्यापित! 50 कॉइन वॉलेट में जोड़े गए।",
        "task_already_done" to "यह टास्क पहले ही पूर्ण हो चुका है।",
        "follow_instagram_title" to "@devrajlohar0981 को फॉलो करें",
        "follow_instagram_desc" to "इंस्टाग्राम पर devrajlohar0981 को फॉलो करें और 50 कॉइन कमाएं",
        "subscribe_youtube_title" to "total video DK सब्सक्राइब करें",
        "subscribe_youtube_desc" to "यूट्यूब पर 'total video DK' सब्सक्राइब करें और 50 कॉइन कमाएं",
        "creator_channels" to "ऑफिशियल क्रिएटर चैनल्स",
        "follow_now" to "फॉलो करें",
        "subscribe_now" to "सब्सक्राइब करें",

        // Cool Features in Hindi
        "scratch_card" to "लकी स्क्रैच कार्ड",
        "scratch_to_win" to "स्क्रैच करें और 100 कॉइन तक जीतें!",
        "scratch_now" to "स्क्रैच करें",
        "scratched_today" to "कार्ड स्क्रैच हो चुका है",
        "streak_booster" to "7-दिन स्ट्रीक बूस्टर",
        "streak_desc" to "रोज़ाना चेक-इन करें और 100 तक मुफ़्त कॉइन पाएं!",
        "refer_earn" to "रेफर करें और कमाएं",
        "refer_desc" to "दोस्तों को इनवाइट करें और 100 कॉइन पाएं!",
        "copy_referral" to "कोड कॉपी करें",
        "share_invite" to "व्हाट्सएप पर शेयर करें",
        "leaderboard" to "टॉप अर्नर्स लीडरबोर्ड",
        
        // Wallet & Redeem - Play Store & UPI Cashback
        "wallet_balance" to "वॉलेट बैलेंस",
        "estimated_value" to "रुपये मूल्य",
        "transaction_history" to "लेन-देन इतिहास",
        "filter_all" to "सभी",
        "filter_earned" to "प्राप्त (+)",
        "filter_redeemed" to "रिडीम (-)",
        "choose_reward" to "रिवॉर्ड रिडीम करें",
        "rule_1200_coins" to "1200 कॉइन = ₹20 (प्ले स्टोर / यूपीआई)",
        "insufficient_balance" to "अपर्याप्त बैलेंस। न्यूनतम 600 कॉइन आवश्यक हैं।",
        "payout_method" to "भुगतान विधि चुनें",
        "enter_account" to "विवरण दर्ज करें",
        "submit_redeem" to "रिडीम अनुरोध भेजें",
        "redeem_submitted" to "रिडीम अनुरोध सफलतापूर्वक भेजा गया!",
        "redeem_history" to "रिडीम इतिहास",
        "redeem_code" to "आपका प्ले स्टोर रिडीम कोड",
        "status_processing" to "प्रक्रिया में",
        "status_rejected" to "अस्वीकृत",
        
        // Play Store & UPI Specific
        "play_store_redeem_code" to "प्ले स्टोर रिडीम कोड",
        "upi_instant_cashback" to "यूपीआई कैशबैक",
        "tab_all_rewards" to "सभी रिवॉर्ड",
        "tab_play_store" to "प्ले स्टोर कोड्स",
        "tab_upi" to "यूपीआई कैशबैक",
        "copy_code" to "कोड कॉपी करें",
        "code_copied" to "रिडीम कोड कॉपी हो गया!",
        "open_play_store" to "प्ले स्टोर पर रिडीम करें",
        "upi_utr_ref" to "बैंक UTR संदर्भ नंबर",
        "cashback_credited" to "कैशबैक बैंक में क्रेडिट हो गया",
        "instant_transfer_badge" to "⚡ त्वरित 5-मिनट ट्रांसफर",
        "play_store_instructions" to "कैसे रिडीम करें: प्ले स्टोर खोलें > प्रोफ़ाइल आइकन दबाएं > पेमेंट और सब्सक्रिप्शन > रिडीम कोड दर्ज करें।",
        "upi_cashback_note" to "Google Pay, PhonePe, Paytm या BHIM UPI द्वारा आपके बैंक खाते में सीधा ट्रांसफर।",

        // Profile & Auth
        "login" to "लॉगिन करें",
        "signup" to "साइन अप करें",
        "email" to "ईमेल पता",
        "password" to "पासवर्ड",
        "full_name" to "पूरा नाम",
        "mobile" to "मोबाइल नंबर",
        "sign_in_button" to "साइन इन",
        "create_account" to "खाता बनाएं",
        "quick_test_login" to "त्वरित डेमो लॉगिन (यूज़र)",
        "quick_admin_login" to "त्वरित डेमो लॉगिन (एडमिन)",
        "logout" to "लॉग आउट",
        "account_blocked" to "यह खाता एडमिन द्वारा ब्लॉक कर दिया गया है।",
        "admin_dashboard" to "एडमिन डैशबोर्ड",
        "app_language" to "ऐप की भाषा",
        "dark_mode" to "डार्क मोड",
        
        // Admin
        "admin_panel" to "एडमिन कंट्रोल पैनल",
        "overview" to "अवलोकन",
        "users" to "उपयोगकर्ता",
        "redeem_requests" to "रिडीम अनुरोध",
        "redeem_codes" to "रिडीम कोड्स",
        "manage_quizzes" to "क्विज़ एवं टास्क",
        "total_users" to "कुल उपयोगकर्ता",
        "coins_in_circ" to "कुल कॉइन्स चलन में",
        "pending_redemptions" to "लंबित रिडीम",
        "total_paid_out" to "कुल भुगतान (₹)",
        "approve" to "स्वीकारें और रिवॉर्ड भेजें",
        "reject" to "अस्वीकारें और रिफंड करें",
        "add_code" to "नया कोड जोड़ें",
        "code_input" to "उदा: 3K7X-9PLQ-8B2M-W4TN",
        "block_user" to "यूज़र ब्लॉक करें",
        "unblock_user" to "यूज़र अनब्लॉक करें"
    )
}
